config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#index'
  resources :movies do
    member do
      post '/comments' => 'movies#create_comment'
    end
    
    collection do
      delete '/comments/:comment_id' => 'movies#destroy_comment'
      patch  '/comments/:comment_id' => 'movies#update_comment'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get   '/likes/:movie_id' => 'movies#like_movie'
  # post  '/movies/:movie_id/comments' => 'movies#comments'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to  :movie
    belongs_to  :user
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
    mount_uploader :image_path,ImageUploader
    has_many   :likes
    has_many   :users,through: :likes
    has_many   :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many    :likes       
  has_many    :movies, through: :likes
  has_many    :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def js_authenticate_user!
    render js: "location.href='/users/sign_in'" unless user_signed_in?
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :js_authenticate_user!, only: [:like_movie]
  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_movie, only: [:show, :edit, :update, :destroy,:create_comment]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @user_likes_movie = Like.where(user_id: current_user.id, movie_id: @movie.id).first if user_signed_in?
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_movie
    p params
    #현재 유저와 params에 담긴 movie 간의
    #좋아요 관계를 설정한다.
      
    #where의 결과값은 배열이다.
    #따라서 .first를 이용해 맨 앞 한가지만.
    @like = Like.where(user_id: current_user.id,movie_id: params[:movie_id]).first
  
    if @like.nil?
      #새로 누른 경우
      #좋아요 관계 설정
      @like = Like.create(user_id: current_user.id,movie_id: params[:movie_id])
      puts "좋아요 설정 끝"
    else
      #만약에 현재 로그인한 유저가 이미 좋아요를 눌렀을 경우
      #해당 Like 인스턴스 삭제
      @like.destroy
    end
    puts @like.frozen?
    
  end

  def create_comment
    @comment = Comment.create(user_id: current_user.id,movie_id: @movie.id,contents: params[:contents])
    # => @movie.comments.new(user_id: current_user.id,contents: params[:contents])
  end
  
  def destroy_comment
    @comment = Comment.find(params[:comment_id]).destroy
  end
  
  def update_comment
    @comment = Comment.find(params[:comment_id])
    @comment.update(contents: params[:contents])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title,:genre,:director,:actor,:description,:image_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchaApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |k,v| %>
      <div class="alert alert-<%= k %>"><%= v %> </div>
    <% end %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :genre %>
    <%= f.text_field :genre, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :director %>
    <%= f.text_field :director, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :actor %>
    <%= f.text_field :actor, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :image_path %>
    <%= f.file_field :image_path, class: "form-control" %>
  </div>
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/create_comment.js.erb
$('.comment-list').append(` <li class="comment-<%=@comment.id%> list-group-item d-flex justify-content-between">
            <span class="comment-detail-<%=@comment.id%>"><%=@comment.contents%></span>
            <div>
                <button data-id="<%=@comment.id%>" class="btn btn-warning text-white edit-comment">수정</button>
                <button data-id="<%=@comment.id%>" class="btn btn-danger destroy-comment">삭제</button>
            </div>
        </li>`);
$('.comment-contents').val('');
alert("댓글 등록이 완료됐습니다.");

app/views/movies/destroy_comment.js.erb
alert("댓글이 삭제 되었습니다.");
$('.comment-<%= @comment.id%>').remove();

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1 id="title">Movies</h1>
<div id="title" class ="row">
<% @movies.each do |movie| %>
<div class="card col-md-3">
  <img class="card-img-top" src="<%=movie.image_path.thumb.url%>" alt="<%=movie.title%>">
  <div id ="mydiv" class="card-body">
    <h5 class="card-title"><span><%= movie.title%></span></h5>
    <p class="card-text">장르:<%=movie.genre%></p>
    <p class="card-text">주연배우:<%=movie.actor%></p>
    <p class="card-text">감독:<%=movie.director%></p>
    <%= link_to '영화 정보보기',movie_path(movie.id),class: 'btn btn-primary'%>
  </div>
</div>
<% end %>
</div>
<br>

<%= link_to 'New Movie', new_movie_path %>
<hr>
<%if user_signed_in? %>
  <!--로그인 된 상태 -->
  <%=current_user.email%>
  <%= link_to "로그아웃",destroy_user_session_path,method: "delete" %>
<% else %>
  <%= link_to "로그인",new_user_session_path %>
<% end %>

<script>
  //func1();
  //func2();


  // var func1 = function(){
  //   alert("안녕 1 ~~");
  // }
  // function func2(){
  //   alert("안녕 2~~");
  // }
  
  // func1();
  // func2();
// var btn = document.getElementsByClassName("btn")[0];
// btn.addEventListener("mouseover",func2);
 
// var btn2 = document.getElementsByClassName("btn")[1];
// btn2.onmouseover = func1;
   
   //버튼(요소)에 마우스를 오버(이벤트)했더니 (이벤트리스너)
   //그 위에 글자(요소)들이 갑자기 이상한 글자로 변해버린다(이벤트핸들러).
  // var btn = document.getElementsByClassName("btn")[0];
  // var str = "";
  // btn.addEventListener("mouseover",function(){
  //   var title = document.getElementsByClassName("card-title")[0];
  //   console.dir(title);
  //   str = title.innerText;
  //   //title.innerText = "Don't Touch me....";
  // });
  
  // btn.addEventListener("mouseout",function(){
  //   var title = document.getElementsByClassName("card-title")[0];
  //   title.innerText = str;
  // });
  
  //버튼(요소)에 마우스를 올리면 (이벤트,이벤트 리스너)
  //해당 버튼(요소)의 class가 btn btn-danger로 변함(이벤트핸들러)
  // var btn = document.getElementsByClassName("btn")[0];
  // btn.addEventListener("mouseover",function(){
  //   btn.setAttribute("class","btn btn-danger");
  // })
  // btn.addEventListener("mouseout",function(){
  //   btn.setAttribute("class","btn btn-primary");
  // }) 
  
</script>

app/views/movies/like_movie.js.erb
alert("좋아요가 설정되었습니다.");

var like_count = parseInt($('.like-count').text());

//좋아요가 취소된 경우
// 좋아요 취소버튼 -> 좋아요 버튼으로
if(<%=@like.frozen? %>) {
    like_count = like_count  - 1;
    $('.like').html(`좋아요(<span class='like-count'>${like_count}</span>)`).removeClass("btn-warning text-white").addClass("btn-info");
} else{
//좋아요가 새로 눌린 경우
//좋아요 버튼 -> 좋아요 취소버튼으로
    like_count = like_count  + 1;
    $('.like').html(`좋아요 취소(<span class='like-count'>${like_count}</span>)`).removeClass("btn-info").addClass("btn-warning text-white");
}

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<p align="right"><%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %></p>
<hr>
<p><%= @movie.description %></p>


<hr>
<% if @user_likes_movie.nil? %>
    <button class="btn btn-info like">좋아요(<span class="like-count"><%=@movie.likes.count%></span>)</button>
<% else %>  
    <button class="btn btn-warning text-white like">좋아요 취소(<span class="like-count"><%=@movie.likes.count%></span>)</button>
<% end %> 
<hr>
<form class = "text-right comment">
    <input class="form-control comment-contents"><br>
    <input type = "submit" value="댓글쓰기" class = "btn btn-success">
</form>
<h3>댓글 목록</h3>
<hr>

<ul class="list-group comment-list">
    <!-- 기존에 등록되어있는 댓글 출력하기-->
    <% @movie.comments.each do |comment| %>
        <li class='comment-<%=comment.id%> list-group-item d-flex justify-content-between'>
            <span class="comment-detail-<%=comment.id%>"><%=comment.contents%></span>
            <div>
                <button data-id="<%=comment.id%>" class="btn btn-warning text-white edit-comment">수정</button>
                <button data-id="<%=comment.id%>" class="btn btn-danger destroy-comment">삭제</button>
            </div>
        </li>
    <% end %>
</ul>

<script>
$(document).on('ready',function(){
    
  $('.like').on('click',function(){

    // $( this ).find( "span" ).text( "clicks: " + count );
    console.log("like!!!");

    $.ajax({
       url: '/likes/<%= @movie.id %>' 
    });
  });
  
  $('.comment').on('submit',function(e){
      e.preventDefault();        //이벤트 중지
     var comm = $('.comment-contents').val();

     //순서대로 입력
    // $('.comment-list').append(`<li class="list-group-item">${comm}</li>`);
    
    //역순으로 입력
     $.ajax({
       method: "POST",
       url: "/movies/<%= @movie.id %>/comments", 
       data: {
           contents: comm
       }
    });
  });
 
 $(document).on('click','.destroy-comment',function(){
    console.log("detroyed!!!");
   
    var comment_id = $(this).attr('data-id');
    // = $(this).data('id')
    console.log(comment_id);
    $.ajax({
        method:"DELETE",
        url: "/movies/comments/" + comment_id
    })
  });   
  
    $(document).on('click','.edit-comment', function(){//수정 (1)
       //console.log($(this).parent().parent().find('.comment-detail'));아래와 동일
        if(!$('.update-comment').length){
            var comment_id = $(this).data('id');
            var edit_comment = $(`.comment-detail-${comment_id}`);
            var contents = edit_comment.text().trim();
            edit_comment.html(`
            <input type="text" value="${contents}" class="form-control edit-comment-${comment_id}">`);//(2)
            $(this).text("확인").removeClass("edit-comment btn-warning").addClass("update-comment btn-dark")//(3)
            
        }
        else{
            alert("수정은 한개만 된다.");
        }
        
      
    });
    
    $(document).on('click','.update-comment', function(){//(4)
        var comment_id = $(this).data('id');
        var comment_form = $(`.edit-comment-${comment_id}`)
         
         $.ajax({
            url: "/movies/comments/" + comment_id,
            method: "patch",
            data:{
                contents: comment_form.val()
            }
         });
    });
}); 

</script>

app/views/movies/update_comment.js.erb
alert("수정완료");
var edit_comment = $('.comment-detail-<%=@comment.id%>');
edit_comment.html('<%=@comment.contents%>');
$('.update-comment').text("수정").removeClass("update-comment btn-dark").addClass("edit-comment btn-warning");